### ISSUE TITLE
Cannot find module './formats'

### ISSUE THREAD

**Issue by AdamSEY** [japandotorg/videolinkapi#1]
This file seems to be missing.

**Comment by Bestulo** [comment]
still missing lmao

**Comment by Bestulo** [comment]
I solved this @AdamSEY, i used the file directly without importing from the module. I added the file to my `./lib` folder as `twitterDownloader.ts` and imported directly from it. Now everything works correctly.

**Comment by japandotorg** [comment]
I'll be doing a re-write to fix all these import issues, might take a while but PRs are always open.

**Comment by japandotorg** [comment]
@AdamSEY @Bestulo I've fixed the `./formats` import issue, I'll be pushing changes into npm when I'm home later tonight, till then y'all can build from source if anything important or sum
